# Generated by Django 5.0.2 on 2024-02-19 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_projectmanager_project_project_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Project_manager',
            new_name='projectmanager',
        ),
    ]
